#!/bin/bash

# =============================================================================
# DEPLOY SCRIPT FOR LIDER GARANT
# Server: 85.198.97.62
# Domains: lider-garant.ru, www.lider-garant.ru, lk.lider-garant.ru
# =============================================================================
#
# Features:
#   - All code from YOUR repository (no external submodules)
#   - Real SSL certificates via Let's Encrypt
#   - Database preserved between deploys (Docker volume)
#   - Safe container management (no data loss)
#
# =============================================================================

set -e  # Exit on error

REPO_URL="https://github.com/Nevern1y/vashmarketolog"
PROJECT_DIR="/opt/vashmarketolog"
DOMAINS="lider-garant.ru www.lider-garant.ru lk.lider-garant.ru"
EMAIL="admin@lider-garant.ru"  # For Let's Encrypt notifications

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== ДЕПЛОЙ LIDER GARANT на сервер 85.198.97.62 ===${NC}"
echo ""

# =============================================================================
# Шаг 1: Установка зависимостей
# =============================================================================
echo -e "${YELLOW}Шаг 1: Проверка и установка зависимостей...${NC}"
apt update -qq
apt install -y git docker.io docker-compose-plugin curl

# Ensure Docker is running
systemctl enable docker
systemctl start docker

echo -e "${GREEN}✓ Зависимости установлены${NC}"
echo ""

# =============================================================================
# Шаг 2: Клонирование/обновление репозитория
# =============================================================================
echo -e "${YELLOW}Шаг 2: Синхронизация репозитория...${NC}"
if [ -d "$PROJECT_DIR/.git" ]; then
    echo "Обновление существующего репозитория..."
    cd "$PROJECT_DIR"
    git fetch origin
    git reset --hard origin/main
    git clean -fd
else
    echo "Первоначальное клонирование репозитория..."
    rm -rf "$PROJECT_DIR"
    git clone "$REPO_URL" "$PROJECT_DIR"
    cd "$PROJECT_DIR"
fi

echo -e "${GREEN}✓ Репозиторий синхронизирован${NC}"
echo ""

# =============================================================================
# Шаг 3: Создание/обновление .env файла
# =============================================================================
echo -e "${YELLOW}Шаг 3: Настройка переменных окружения...${NC}"

# Check if .env exists and has real credentials
if [ -f "$PROJECT_DIR/.env" ] && grep -q "^SECRET_KEY=" "$PROJECT_DIR/.env"; then
    echo "Используем существующий .env файл"
else
    echo "Создание .env файла..."
    # Generate secure secret key
    SECRET_KEY=$(openssl rand -base64 50 | tr -dc 'a-zA-Z0-9' | head -c 64)
    DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
    
    cat > "$PROJECT_DIR/.env" << ENVEOF
# Generated by deploy-server.sh on $(date)
SECRET_KEY=$SECRET_KEY
DB_NAME=lider_garant
DB_USER=postgres
DB_PASSWORD=$DB_PASSWORD
DB_HOST=db
DB_PORT=5432
REDIS_HOST=redis
REDIS_PORT=6379
ALLOWED_HOSTS=.lider-garant.ru,lk.lider-garant.ru,85.198.97.62,localhost
CORS_ALLOWED_ORIGINS=https://lk.lider-garant.ru,https://lider-garant.ru
BANK_API_URL=https://stagebg.realistbank.ru/agent_api1_1
BANK_API_LOGIN=
BANK_API_PASSWORD=
SECURE_SSL_REDIRECT=False
ACCESS_TOKEN_LIFETIME_MINUTES=60
REFRESH_TOKEN_LIFETIME_DAYS=7
ENVEOF

    echo -e "${YELLOW}ВНИМАНИЕ: Обновите BANK_API_LOGIN и BANK_API_PASSWORD в $PROJECT_DIR/.env${NC}"
fi

echo -e "${GREEN}✓ Переменные окружения настроены${NC}"
echo ""

# =============================================================================
# Шаг 4: Проверка/получение SSL сертификатов (Let's Encrypt)
# =============================================================================
echo -e "${YELLOW}Шаг 4: Настройка SSL сертификатов...${NC}"

CERT_PATH="$PROJECT_DIR/certbot/conf/live/lider-garant.ru"

if [ -f "$CERT_PATH/fullchain.pem" ] && [ -f "$CERT_PATH/privkey.pem" ]; then
    echo "SSL сертификаты уже существуют"
    
    # Check certificate expiry
    EXPIRY=$(openssl x509 -enddate -noout -in "$CERT_PATH/fullchain.pem" 2>/dev/null | cut -d= -f2)
    echo "Срок действия сертификата: $EXPIRY"
    
    # Create symlinks for nginx
    mkdir -p "$PROJECT_DIR/nginx/ssl"
    ln -sf "$CERT_PATH/fullchain.pem" "$PROJECT_DIR/nginx/ssl/fullchain.pem"
    ln -sf "$CERT_PATH/privkey.pem" "$PROJECT_DIR/nginx/ssl/privkey.pem"
    
    USE_SSL=true
else
    echo "SSL сертификаты не найдены. Получаем через Let's Encrypt..."
    
    # Create directories
    mkdir -p "$PROJECT_DIR/certbot/conf"
    mkdir -p "$PROJECT_DIR/certbot/www"
    mkdir -p "$PROJECT_DIR/nginx/ssl"
    
    # Stop any running nginx
    docker stop lider_prod_nginx 2>/dev/null || true
    
    # Start temporary nginx for ACME challenge
    echo "Запуск временного nginx для получения сертификата..."
    docker run -d --rm --name certbot_nginx \
        -p 80:80 \
        -v "$PROJECT_DIR/nginx/nginx-init.conf:/etc/nginx/nginx.conf:ro" \
        -v "$PROJECT_DIR/certbot/www:/var/www/certbot:ro" \
        nginx:alpine
    
    sleep 3
    
    # Get certificate from Let's Encrypt
    echo "Запрос сертификата у Let's Encrypt..."
    docker run --rm \
        -v "$PROJECT_DIR/certbot/conf:/etc/letsencrypt" \
        -v "$PROJECT_DIR/certbot/www:/var/www/certbot" \
        certbot/certbot certonly \
        --webroot \
        --webroot-path=/var/www/certbot \
        --email "$EMAIL" \
        --agree-tos \
        --no-eff-email \
        -d lider-garant.ru \
        -d www.lider-garant.ru \
        -d lk.lider-garant.ru
    
    # Stop temporary nginx
    docker stop certbot_nginx 2>/dev/null || true
    
    if [ -f "$CERT_PATH/fullchain.pem" ]; then
        echo -e "${GREEN}✓ SSL сертификаты успешно получены!${NC}"
        
        # Create symlinks for nginx
        ln -sf "$CERT_PATH/fullchain.pem" "$PROJECT_DIR/nginx/ssl/fullchain.pem"
        ln -sf "$CERT_PATH/privkey.pem" "$PROJECT_DIR/nginx/ssl/privkey.pem"
        
        USE_SSL=true
    else
        echo -e "${RED}✗ Не удалось получить SSL сертификаты${NC}"
        echo "Проверьте, что домены lider-garant.ru, www.lider-garant.ru, lk.lider-garant.ru"
        echo "направлены на IP адрес этого сервера (85.198.97.62)"
        echo ""
        echo "Создаем временный self-signed сертификат..."
        
        openssl req -x509 -nodes -days 90 -newkey rsa:2048 \
            -keyout "$PROJECT_DIR/nginx/ssl/privkey.pem" \
            -out "$PROJECT_DIR/nginx/ssl/fullchain.pem" \
            -subj "/C=RU/ST=Moscow/L=Moscow/O=LiderGarant/OU=IT/CN=lider-garant.ru"
        
        USE_SSL=true
        echo -e "${YELLOW}Временный сертификат создан. Перезапустите скрипт после настройки DNS.${NC}"
    fi
fi

echo ""

# =============================================================================
# Шаг 5: Остановка контейнеров (БЕЗ удаления volumes!)
# =============================================================================
echo -e "${YELLOW}Шаг 5: Остановка контейнеров...${NC}"

cd "$PROJECT_DIR"

# Stop only our containers, preserve volumes (database!)
docker compose -f docker-compose.prod.yml down 2>/dev/null || true

# Note: We do NOT use "docker compose down -v" - that would delete the database!

echo -e "${GREEN}✓ Контейнеры остановлены (данные сохранены)${NC}"
echo ""

# =============================================================================
# Шаг 6: Сборка и запуск
# =============================================================================
echo -e "${YELLOW}Шаг 6: Сборка и запуск контейнеров...${NC}"

docker compose -f docker-compose.prod.yml up -d --build

echo -e "${GREEN}✓ Контейнеры запущены${NC}"
echo ""

# =============================================================================
# Шаг 7: Ожидание готовности сервисов
# =============================================================================
echo -e "${YELLOW}Шаг 7: Проверка готовности сервисов...${NC}"

# Wait for services to be ready
sleep 10

# Check container status
echo ""
echo "Статус контейнеров:"
docker compose -f docker-compose.prod.yml ps

echo ""

# Test endpoints
echo "Проверка доступности:"

if curl -s -o /dev/null -w "%{http_code}" http://localhost:80 | grep -q "200\|301\|302"; then
    echo -e "${GREEN}✓ HTTP (port 80) - OK${NC}"
else
    echo -e "${YELLOW}⚠ HTTP (port 80) - проверьте логи${NC}"
fi

if curl -sk -o /dev/null -w "%{http_code}" https://localhost:443 | grep -q "200\|301\|302"; then
    echo -e "${GREEN}✓ HTTPS (port 443) - OK${NC}"
else
    echo -e "${YELLOW}⚠ HTTPS (port 443) - проверьте логи${NC}"
fi

echo ""

# =============================================================================
# Завершение
# =============================================================================
echo -e "${GREEN}=== ДЕПЛОЙ ЗАВЕРШЕН ===${NC}"
echo ""
echo "Приложение доступно по адресам:"
echo -e "  ${GREEN}https://lider-garant.ru${NC}     - Лендинг"
echo -e "  ${GREEN}https://lk.lider-garant.ru${NC}  - Личный кабинет"
echo ""
echo "Полезные команды:"
echo "  Логи:     docker compose -f docker-compose.prod.yml logs -f"
echo "  Статус:   docker compose -f docker-compose.prod.yml ps"
echo "  Рестарт:  docker compose -f docker-compose.prod.yml restart"
echo ""
echo "База данных:"
echo "  Volume 'postgres_data' сохраняется между деплоями"
echo "  Для backup: docker exec lider_prod_db pg_dump -U postgres lider_garant > backup.sql"
echo ""

# Show SSL certificate info
if [ -f "$CERT_PATH/fullchain.pem" ]; then
    EXPIRY=$(openssl x509 -enddate -noout -in "$CERT_PATH/fullchain.pem" | cut -d= -f2)
    echo "SSL сертификат действителен до: $EXPIRY"
    echo "Сертификат будет автоматически обновляться контейнером certbot"
fi
