# Generated by Django 6.0 on 2026-01-16 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('decision_approved', 'Заявка одобрена'), ('decision_rejected', 'Заявка отклонена'), ('decision_info_requested', 'Запрошена информация'), ('status_change', 'Изменение статуса заявки'), ('new_application', 'Новая заявка'), ('document_verified', 'Документ проверен'), ('document_rejected', 'Документ отклонён'), ('document_requested', 'Запрос документа'), ('chat_message', 'Новое сообщение')], db_index=True, max_length=30, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Структурированные данные уведомления (application_id, document_id и т.д.)', verbose_name='Дополнительные данные')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID источника')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип источника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
