# Generated by Django 6.0 on 2026-02-10 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_add_admin_new_client_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, db_index=True, default='generic', max_length=64, verbose_name='Тип события')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Отправитель')),
                ('recipient_list', models.JSONField(default=list, verbose_name='Получатели')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Не отправлено')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('max_attempts', models.PositiveIntegerField(default=30, verbose_name='Макс. попыток')),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Следующая попытка')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Письмо в outbox',
                'verbose_name_plural': 'Outbox SMTP',
                'ordering': ['next_retry_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_999910_idx'), models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_9c8a01_idx')],
            },
        ),
    ]
