# Generated by Django 5.0.4 on 2026-02-02 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_conditions', '0002_populate_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='bank',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bank',
            name='partner_user',
            field=models.OneToOneField(blank=True, help_text='Пользователь с ролью partner, связанный с этим банком', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_bank', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт партнёра'),
        ),
    ]
