# Generated by Django 6.0 on 2025-12-29 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accreditation_comment',
            field=models.TextField(blank=True, default='', help_text='Причина отклонения или примечания', verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='user',
            name='accreditation_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='user',
            name='accreditation_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accreditations', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='user',
            name='accreditation_status',
            field=models.CharField(choices=[('none', 'Не подана'), ('pending', 'На проверке'), ('approved', 'Аккредитован'), ('rejected', 'Отклонена')], default='none', help_text='Статус аккредитации агента (только для роли Agent)', max_length=20, verbose_name='Статус аккредитации'),
        ),
        migrations.AddField(
            model_name='user',
            name='accreditation_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи аккредитации'),
        ),
    ]
