# Generated by Django 5.0.4 on 2025-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_crm_client', models.BooleanField(default=False, help_text='True = клиент агента (CRM), False = собственная компания', verbose_name='CRM клиент')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, default='', max_length=15, verbose_name='ОГРН')),
                ('name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Краткое наименование')),
                ('legal_address', models.TextField(blank=True, default='', verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, default='', verbose_name='Фактический адрес')),
                ('director_name', models.CharField(blank=True, default='', max_length=300, verbose_name='ФИО руководителя')),
                ('director_position', models.CharField(blank=True, default='', max_length=100, verbose_name='Должность руководителя')),
                ('bank_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Наименование банка')),
                ('bank_bic', models.CharField(blank=True, default='', max_length=9, verbose_name='БИК')),
                ('bank_account', models.CharField(blank=True, default='', max_length=20, verbose_name='Расчётный счёт')),
                ('bank_corr_account', models.CharField(blank=True, default='', max_length=20, verbose_name='Корр. счёт')),
                ('contact_person', models.CharField(blank=True, default='', max_length=300, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон контактного лица')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email контактного лица')),
                ('website', models.URLField(blank=True, default='', verbose_name='Веб-сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профили компаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
