# Generated by Django 6.0 on 2025-12-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank_accounts_data',
            field=models.JSONField(blank=True, default=list, help_text='Список счетов: [{"account": "р/с", "bic": "БИК", "bank_name": "Банк"}]', verbose_name='Банковские счета (JSON)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='founders_data',
            field=models.JSONField(blank=True, default=list, help_text='Список учредителей: [{"name": "ФИО", "inn": "ИНН", "share": доля%}]', verbose_name='Учредители (JSON)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='passport_code',
            field=models.CharField(blank=True, help_text='Код подразделения (формат: XXX-XXX)', max_length=7, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='passport_issued_by',
            field=models.TextField(blank=True, help_text='Орган, выдавший паспорт', null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='passport_number',
            field=models.CharField(blank=True, help_text='6 цифр номера паспорта', max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='passport_series',
            field=models.CharField(blank=True, help_text='4 цифры серии паспорта', max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
    ]
