# Generated by Django 6.0 on 2025-12-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyprofile_bank_accounts_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Регион'),
        ),
    ]
