# Generated by Django 5.0.4 on 2025-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='bank_accounts_data',
            field=models.JSONField(blank=True, default=list, help_text='Список банковских счетов:\n        [{\n            "bank_name": "АО РЕАЛИСТ БАНК",\n            "bank_bik": "044525285",\n            "account": "40702810000000000000"\n        }]', verbose_name='Банковские счета (JSON)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='founders_data',
            field=models.JSONField(blank=True, default=list, help_text='Список учредителей для Phase 2 интеграции:\n        [{\n            "full_name": "ФИО",\n            "inn": "ИНН",\n            "share_relative": доля%,\n            "document": {\n                "series": "серия паспорта",\n                "number": "номер паспорта",\n                "issued_at": "YYYY-MM-DD",\n                "authority_name": "Кем выдан",\n                "authority_code": "XXX-XXX"\n            },\n            "birth_place": "Место рождения",\n            "birth_date": "YYYY-MM-DD",\n            "gender": 1 или 2,\n            "citizen": "РФ"\n        }]', verbose_name='Учредители (JSON)'),
        ),
    ]
