# Generated by Django 6.0 on 2025-12-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companyprofile_bank_accounts_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='signatory_basis',
            field=models.CharField(blank=True, choices=[('charter', 'Устава'), ('power_of_attorney', 'Доверенности')], default='charter', max_length=20, verbose_name='Действует на основании'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tax_system',
            field=models.CharField(blank=True, choices=[('osn', 'ОСН (Общая)'), ('usn_income', 'УСН (Доходы)'), ('usn_income_expense', 'УСН (Доходы-Расходы)'), ('esn', 'ЕСХН'), ('patent', 'ПСН (Патент)')], max_length=20, null=True, verbose_name='Система налогообложения'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vat_rate',
            field=models.CharField(blank=True, choices=[('none', 'НДС не облагается'), ('0', '0%'), ('5', '5%'), ('7', '7%'), ('10', '10%'), ('20', '20%')], max_length=10, null=True, verbose_name='Ставка НДС'),
        ),
    ]
