# Generated by Django 6.0 on 2025-12-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyprofile_signatory_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='activities_data',
            field=models.JSONField(blank=True, default=list, help_text='Виды деятельности и ОКВЭД:\n        [{\n            "code": "62.01",\n            "name": "Разработка компьютерного ПО",\n            "is_primary": true\n        }]', verbose_name='Деятельность/ОКВЭД (JSON)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='actual_address_postal_code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Индекс факт. адреса'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='authorized_capital_declared',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Объявленный уставный капитал'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='authorized_capital_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Оплаченный уставный капитал'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='authorized_capital_paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения оплаченного УК'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email компании'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_website',
            field=models.URLField(blank=True, default='', verbose_name='Сайт компании'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_persons_data',
            field=models.JSONField(blank=True, default=list, help_text='Список контактных лиц:\n        [{\n            "position": "Должность",\n            "last_name": "Фамилия",\n            "first_name": "Имя",\n            "patronymic": "Отчество",\n            "email": "email@example.com",\n            "phone": "+7..."\n        }]', verbose_name='Контактные лица (JSON)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contracts_223fz_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контрактов по 223-ФЗ'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contracts_44fz_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контрактов по 44-ФЗ'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contracts_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество контрактов'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='etp_accounts_data',
            field=models.JSONField(blank=True, default=list, help_text='Реквизиты счетов на электронных площадках:\n        [{\n            "platform": "ЕЭТП (roseltorg.ru)",\n            "account": "40702810...",\n            "bik": "044525285",\n            "bank_name": "Сбербанк",\n            "corr_account": "30101810..."\n        }]', verbose_name='Счета ЭТП (JSON)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='foreign_name',
            field=models.CharField(blank=True, default='', help_text='Наименование на иностранном языке (если имеется)', max_length=500, verbose_name='Наименование на иностранном языке'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_resident',
            field=models.BooleanField(default=True, help_text='Является ли резидентом РФ', verbose_name='Резидент РФ'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='leadership_data',
            field=models.JSONField(blank=True, default=list, help_text='Список руководителей компании:\n        [{\n            "position": "Должность",\n            "full_name": "ФИО",\n            "share_percent": доля%,\n            "citizenship": "РФ",\n            "birth_date": "YYYY-MM-DD",\n            "birth_place": "Место рождения",\n            "email": "email@example.com",\n            "phone": "+7...",\n            "passport": {\n                "document_type": "passport_rf",\n                "series": "1234",\n                "number": "567890",\n                "issued_date": "YYYY-MM-DD",\n                "issued_by": "Кем выдан",\n                "department_code": "XXX-XXX",\n                "registration_address": "Адрес"\n            }\n        }]', verbose_name='Руководство (JSON)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_address_postal_code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Индекс юр. адреса'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_form',
            field=models.CharField(blank=True, default='', help_text='ООО, АО, ИП и т.д.', max_length=100, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='licenses_data',
            field=models.JSONField(blank=True, default=list, help_text='СРО и лицензии:\n        [{\n            "type": "СРО",\n            "name": "Наименование",\n            "number": "Номер",\n            "issued_date": "YYYY-MM-DD",\n            "valid_until": "YYYY-MM-DD"\n        }]', verbose_name='Лицензии (JSON)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='office_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тел. офиса'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='okato',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='ОКАТО'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='okfs',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='ОКФС'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='okogu',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ОКОГУ'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='okpo',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='oktmo',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='ОКТМО'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='okved',
            field=models.TextField(blank=True, default='', verbose_name='ОКВЭД (основной)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='post_address',
            field=models.TextField(blank=True, default='', help_text='Адрес для корреспонденции', verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='post_address_postal_code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Индекс почт. адреса'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registration_authority',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Наименование регистрирующего органа'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата гос. регистрации'),
        ),
    ]
