# Generated by Django 6.0 on 2026-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_add_client_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='director_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения руководителя'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='director_birth_place',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Место рождения руководителя'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='director_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email руководителя'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='director_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон руководителя'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='director_registration_address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес регистрации руководителя'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='oktmo_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановки ОКТМО'),
        ),
    ]
