# Generated by Django 6.0 on 2026-01-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_director_fields_and_oktmo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_accredited',
            field=models.BooleanField(default=False, help_text='True если клиент прошёл аккредитацию (заполнил профиль и загрузил документы)', verbose_name='Аккредитован'),
        ),
    ]
