# Generated by Django 5.0.4 on 2026-01-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_add_is_accredited'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='legal_founders_data',
            field=models.JSONField(blank=True, default=list, help_text='Список учредителей (юр.лица):\n        [{\n            "share_relative": 10,\n            "inn": "77...",\n            "ogrn": "102...",\n            "name": "ООО Ромашка",\n            "registration_date": "YYYY-MM-DD",\n            "first_registration_date": "YYYY-MM-DD",\n            "is_resident": true,\n            "bank_name": "Сбер",\n            "website": "...",\n            "email": "...",\n            "phone": "...",\n            "director_position": "Гендир",\n            "director_name": "Иванов И.И."\n        }]', verbose_name='Учредители - Юр.лица (JSON)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='founders_data',
            field=models.JSONField(blank=True, default=list, help_text='Список учредителей для Phase 2 интеграции:\n        [{\n            "full_name": "ФИО",\n            "inn": "ИНН",\n            "share_relative": доля%,\n            "document": {\n                "series": "серия паспорта",\n                "number": "номер паспорта",\n                "issued_at": "YYYY-MM-DD",\n                "authority_name": "Кем выдан",\n                "authority_code": "XXX-XXX"\n            },\n            "birth_place": "Место рождения",\n            "birth_date": "YYYY-MM-DD",\n            "gender": 1 или 2,\n            "citizen": "РФ",\n            "legal_address": {"value": "...", "postal_code": "..."},\n            "is_resident": true/false\n        }]', verbose_name='Учредители (JSON)'),
        ),
    ]
