# Generated by Django 6.0 on 2026-01-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_companyprofile_legal_founders_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_mchd',
            field=models.BooleanField(default=False, help_text='Есть ли машиночитаемая доверенность (МЧД)', verbose_name='Есть МЧД'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mchd_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания МЧД'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mchd_file',
            field=models.FileField(blank=True, help_text='XML или PDF файл машиночитаемой доверенности', null=True, upload_to='mchd/%Y/%m/', verbose_name='Файл МЧД'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mchd_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи МЧД'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mchd_number',
            field=models.CharField(blank=True, default='', help_text='Регистрационный номер МЧД', max_length=100, verbose_name='Номер МЧД'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mchd_principal_inn',
            field=models.CharField(blank=True, default='', help_text='ИНН лица, выдавшего доверенность', max_length=12, verbose_name='ИНН доверителя'),
        ),
    ]
