# Generated by Django 5.0.4 on 2026-02-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_mchd_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Определяет, активен ли профиль компании для работы', verbose_name='Активен'),
        ),
    ]
