# Generated by Django 5.0.4 on 2025-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('bank_guarantee', 'Банковская гарантия'), ('tender_loan', 'Тендерный кредит'), ('factoring', 'Факторинг'), ('leasing', 'Лизинг')], max_length=30, verbose_name='Тип продукта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('term_months', models.IntegerField(verbose_name='Срок (месяцы)')),
                ('tender_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер тендера')),
                ('tender_platform', models.CharField(blank=True, default='', max_length=200, verbose_name='Площадка')),
                ('tender_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн тендера')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('in_review', 'В работе'), ('info_requested', 'Запрошена информация'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('won', 'Выигран'), ('lost', 'Проигран')], default='draft', max_length=20, verbose_name='Статус')),
                ('has_signature', models.BooleanField(default=False, verbose_name='Есть ЭЦП')),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='signatures/%Y/%m/', verbose_name='Файл ЭЦП')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('info_requested', 'Запрошена информация')], max_length=20, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('offered_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Предложенная ставка %')),
                ('offered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Предложенная сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата решения')),
            ],
            options={
                'verbose_name': 'Решение партнёра',
                'verbose_name_plural': 'Решения партнёров',
                'ordering': ['-created_at'],
            },
        ),
    ]
