# Generated by Django 5.0.4 on 2025-12-26 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный партнёр'),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.companyprofile', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_applications', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='applications', to='documents.document', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='partnerdecision',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='applications.application', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='partnerdecision',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
    ]
