# Generated by Django 6.0 on 2025-12-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='target_bank_name',
            field=models.CharField(blank=True, default='', help_text='Банк, в который планируется направить заявку (для маршрутизации Админом)', max_length=200, verbose_name='Целевой банк'),
        ),
    ]
