# Generated by Django 6.0 on 2025-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
    ]
