# Generated by Django 6.0 on 2025-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_allow_empty_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='goscontract_data',
            field=models.JSONField(blank=True, default=dict, help_text='Структурированные данные о госконтракте для API банка', verbose_name='Данные тендера (JSON)'),
        ),
    ]
