# Generated by Django 5.0.4 on 2025-12-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_goscontract_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='guarantee_type',
            field=models.CharField(blank=True, choices=[('application_security', 'Обеспечение заявки'), ('contract_execution', 'Исполнение контракта'), ('advance_return', 'Возврат аванса'), ('warranty_obligations', 'Гарантийные обязательства'), ('payment_guarantee', 'Гарантии оплаты товара'), ('customs_guarantee', 'Таможенные гарантии'), ('vat_refund', 'Возмещение НДС')], default='', help_text='Тип БГ (только для bank_guarantee)', max_length=30, verbose_name='Тип гарантии'),
        ),
        migrations.AddField(
            model_name='application',
            name='tender_law',
            field=models.CharField(blank=True, choices=[('44_fz', '44-ФЗ'), ('223_fz', '223-ФЗ'), ('615_pp', '615-ПП'), ('185_fz', '185-ФЗ'), ('kbg', 'КБГ (Коммерческая)'), ('commercial', 'Коммерческий')], default='', help_text='Федеральный закон (44-ФЗ, 223-ФЗ, 185-ФЗ, КБГ)', max_length=20, verbose_name='Закон о закупках'),
        ),
    ]
