# Generated by Django 6.0 on 2025-12-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_guarantee_type_application_tender_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='credit_sub_type',
            field=models.CharField(blank=True, choices=[('one_time_credit', 'Разовый кредит'), ('non_revolving_line', 'Невозобновляемая КЛ'), ('revolving_line', 'Возобновляемая КЛ'), ('overdraft', 'Овердрафт')], default='', help_text='Подтип кредита (только для corporate_credit)', max_length=30, verbose_name='Тип кредита'),
        ),
        migrations.AddField(
            model_name='application',
            name='financing_term_days',
            field=models.IntegerField(blank=True, help_text='Срок финансирования в днях (альтернатива term_months)', null=True, verbose_name='Срок в днях'),
        ),
        migrations.AddField(
            model_name='application',
            name='pledge_description',
            field=models.TextField(blank=True, default='', help_text='Обеспечение/залог: недвижимость, транспорт, депозит и т.д.', verbose_name='Описание залога'),
        ),
        migrations.AlterField(
            model_name='application',
            name='product_type',
            field=models.CharField(choices=[('bank_guarantee', 'Банковская гарантия'), ('tender_loan', 'Тендерный кредит'), ('contract_loan', 'Кредит на исполнение контракта'), ('corporate_credit', 'Корпоративный кредит'), ('factoring', 'Факторинг'), ('leasing', 'Лизинг')], max_length=30, verbose_name='Тип продукта'),
        ),
    ]
