# Generated by Django 6.0 on 2025-12-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_credit_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bank_status',
            field=models.CharField(blank=True, default='new', help_text='Статус заявки в банке (new, sent, scoring, approved, rejected)', max_length=50, verbose_name='Статус в банке'),
        ),
        migrations.AddField(
            model_name='application',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID заявки, возвращённый банком после отправки', max_length=100, null=True, verbose_name='ID заявки в банке'),
        ),
    ]
