# Generated by Django 6.0 on 2025-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_add_bank_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='full_client_data',
            field=models.JSONField(blank=True, default=dict, help_text='Полная структура client[] для API банка (учредители, адреса, счета)', verbose_name='Полные данные клиента (JSON)'),
        ),
    ]
