# Generated by Django 6.0 on 2025-12-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_full_client_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='commission_data',
            field=models.JSONField(blank=True, default=dict, help_text='Структура комиссии от банка: {total, bank, agent, default}', verbose_name='Комиссия (JSON)'),
        ),
        migrations.AddField(
            model_name='application',
            name='signing_url',
            field=models.URLField(blank=True, default='', help_text='URL для подписи документов в банке (из get_ticket_token)', max_length=500, verbose_name='URL для подписи'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_bank_message',
            field=models.BooleanField(default=False, help_text='True если сообщение получено через вебхук TICKET_CHAT_MESSAGE_URL', verbose_name='Сообщение от банка'),
        ),
    ]
