# Generated by Django 6.0 on 2025-12-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_bank_integration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID заявки, возвращённый банком после отправки (ticket_id)', max_length=100, null=True, verbose_name='ID заявки в банке'),
        ),
    ]
