# Generated by Django 6.0 on 2025-12-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_external_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='account_type',
            field=models.CharField(blank=True, default='', help_text='РКО или Спецсчет', max_length=20, verbose_name='Тип счета'),
        ),
        migrations.AddField(
            model_name='application',
            name='contractor_inn',
            field=models.CharField(blank=True, default='', help_text='ИНН дебитора для факторинга', max_length=12, verbose_name='ИНН контрагента'),
        ),
        migrations.AddField(
            model_name='application',
            name='factoring_type',
            field=models.CharField(blank=True, choices=[('classic', 'Классический факторинг'), ('closed', 'Закрытый факторинг'), ('procurement', 'Закупочный факторинг')], default='', help_text='Классический/Закрытый/Закупочный', max_length=20, verbose_name='Тип факторинга'),
        ),
        migrations.AddField(
            model_name='application',
            name='industry',
            field=models.CharField(blank=True, default='', help_text='Интересующая отрасль закупок', max_length=200, verbose_name='Отрасль закупок'),
        ),
        migrations.AddField(
            model_name='application',
            name='insurance_category',
            field=models.CharField(blank=True, choices=[('personnel', 'Персонал'), ('transport', 'Транспорт'), ('property', 'Имущество'), ('liability', 'Ответственность')], default='', help_text='Персонал/Транспорт/Имущество/Ответственность', max_length=30, verbose_name='Категория страхования'),
        ),
        migrations.AddField(
            model_name='application',
            name='insurance_product_type',
            field=models.CharField(blank=True, choices=[('dms', 'Добровольное медицинское страхование (ДМС)'), ('critical_illness', 'Страхование критических заболеваний'), ('accident', 'Страхование несчастных случаев'), ('travel', 'Комплексное страхование в поездках'), ('osago', 'ОСАГО юридических лиц'), ('fleet', 'Комплексное страхование автопарков'), ('special_tech', 'Страхование специальной техники'), ('carrier_liability', 'Страхование ответственности перевозчика'), ('construction', 'Страхование объектов строительства'), ('cargo', 'Страхование грузов и перевозок'), ('company_property', 'Страхование имущества компаний'), ('business_interruption', 'Страхование перерывов деятельности'), ('civil_liability', 'Страхование гражданской ответственности'), ('hazardous_objects', 'Страхование опасных объектов'), ('professional_risks', 'Страхование профессиональных рисков'), ('quality_liability', 'Страхование ответственности за качество')], default='', help_text='Подтип страхования (ДМС, ОСАГО, и т.д.)', max_length=40, verbose_name='Страховой продукт'),
        ),
        migrations.AddField(
            model_name='application',
            name='purchase_category',
            field=models.CharField(blank=True, choices=[('gov_44', 'Госзакупки по 44-ФЗ'), ('gov_223', 'Закупки по 223-ФЗ'), ('property', 'Имущественные торги'), ('commercial', 'Коммерческие закупки')], default='', help_text='44-ФЗ/223-ФЗ/Имущественные/Коммерческие', max_length=20, verbose_name='Категория закупок'),
        ),
        migrations.AddField(
            model_name='application',
            name='tender_support_type',
            field=models.CharField(blank=True, choices=[('one_time', 'Разовое сопровождение'), ('full_cycle', 'Тендерное сопровождение под ключ')], default='', help_text='Разовое/Под ключ', max_length=20, verbose_name='Тип сопровождения'),
        ),
        migrations.AddField(
            model_name='application',
            name='ved_country',
            field=models.CharField(blank=True, default='', help_text='Страна платежа для ВЭД', max_length=100, verbose_name='Страна контрагента'),
        ),
        migrations.AddField(
            model_name='application',
            name='ved_currency',
            field=models.CharField(blank=True, default='', help_text='Валюта платежа (USD, EUR, CNY, RUB)', max_length=10, verbose_name='Валюта ВЭД'),
        ),
        migrations.AlterField(
            model_name='application',
            name='product_type',
            field=models.CharField(choices=[('bank_guarantee', 'Банковская гарантия'), ('tender_loan', 'Тендерный кредит'), ('contract_loan', 'Кредит на исполнение контракта'), ('corporate_credit', 'Корпоративный кредит'), ('factoring', 'Факторинг'), ('leasing', 'Лизинг'), ('ved', 'ВЭД (Валютные операции)'), ('insurance', 'Страхование'), ('rko', 'РКО'), ('special_account', 'Спецсчет'), ('tender_support', 'Тендерное сопровождение')], max_length=30, verbose_name='Тип продукта'),
        ),
    ]
