# Generated by Django 5.0.4 on 2026-01-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_populate_statuses_appendix_a'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationstatusdefinition',
            name='unique_status_per_product',
        ),
        migrations.RenameIndex(
            model_name='applicationstatusdefinition',
            new_name='application_product_eac892_idx',
            old_name='apps_status_prod_idx',
        ),
        migrations.AlterUniqueTogether(
            name='applicationstatusdefinition',
            unique_together={('status_id', 'product_type')},
        ),
    ]
