# Generated by Django 6.0 on 2026-01-12 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_remove_applicationstatusdefinition_unique_status_per_product_and_more'),
        ('companies', '0011_companyprofile_legal_founders_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('bank_guarantee', 'Банковская гарантия'), ('tender_loan', 'Тендерный кредит'), ('contract_loan', 'Кредит на исполнение контракта'), ('corporate_credit', 'Корпоративный кредит'), ('factoring', 'Факторинг'), ('leasing', 'Лизинг'), ('ved', 'ВЭД (Валютные операции)'), ('insurance', 'Страхование'), ('rko', 'РКО'), ('special_account', 'Спецсчет'), ('tender_support', 'Тендерное сопровождение')], max_length=30, verbose_name='Тип продукта')),
                ('form_data', models.JSONField(default=dict, help_text='Данные формы калькулятора: сумма, сроки, закон, тип и т.д.', verbose_name='Данные формы')),
                ('approved_banks', models.JSONField(default=list, help_text='Список одобренных банков с тарифами: [{name, rate, speed, ...}]', verbose_name='Одобренные банки')),
                ('rejected_banks', models.JSONField(default=list, help_text='Список отклонённых банков: [{bank, reason}]', verbose_name='Отклонённые банки')),
                ('submitted_banks', models.JSONField(default=list, help_text='Список банков, по которым созданы заявки', verbose_name='Отправленные банки')),
                ('title', models.CharField(blank=True, default='', help_text='Отображаемый заголовок сессии калькуляции', max_length=200, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_sessions', to='companies.companyprofile', verbose_name='Компания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сессия калькуляции',
                'verbose_name_plural': 'Сессии калькуляции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='calculation_session',
            field=models.ForeignKey(blank=True, help_text='Ссылка на сессию калькуляции (корневую заявку)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.calculationsession', verbose_name='Сессия калькуляции'),
        ),
    ]
