# Generated by Django 6.0 on 2026-01-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_add_calculation_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='product_type',
            field=models.CharField(choices=[('bank_guarantee', 'Банковская гарантия'), ('tender_loan', 'Тендерный кредит'), ('contract_loan', 'Кредит на исполнение контракта'), ('corporate_credit', 'Корпоративный кредит'), ('factoring', 'Факторинг'), ('leasing', 'Лизинг'), ('ved', 'ВЭД (Валютные операции)'), ('insurance', 'Страхование'), ('rko', 'РКО'), ('special_account', 'Спецсчет'), ('tender_support', 'Тендерное сопровождение'), ('deposits', 'Депозиты')], max_length=30, verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='calculationsession',
            name='product_type',
            field=models.CharField(choices=[('bank_guarantee', 'Банковская гарантия'), ('tender_loan', 'Тендерный кредит'), ('contract_loan', 'Кредит на исполнение контракта'), ('corporate_credit', 'Корпоративный кредит'), ('factoring', 'Факторинг'), ('leasing', 'Лизинг'), ('ved', 'ВЭД (Валютные операции)'), ('insurance', 'Страхование'), ('rko', 'РКО'), ('special_account', 'Спецсчет'), ('tender_support', 'Тендерное сопровождение'), ('deposits', 'Депозиты')], max_length=30, verbose_name='Тип продукта'),
        ),
    ]
