# Generated by Django 5.0.4 on 2026-01-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_add_deposits_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('product_type', models.CharField(choices=[('bank_guarantee', 'Банковская гарантия'), ('tender_loan', 'Тендерный кредит'), ('contract_loan', 'Кредит на исполнение контракта'), ('corporate_credit', 'Корпоративный кредит'), ('factoring', 'Факторинг'), ('leasing', 'Лизинг'), ('ved', 'ВЭД (Валютные операции)'), ('insurance', 'Страхование'), ('rko', 'РКО'), ('special_account', 'Спецсчет'), ('tender_support', 'Тендерное сопровождение'), ('deposits', 'Депозиты')], default='bank_guarantee', max_length=30, verbose_name='Тип продукта')),
                ('guarantee_type', models.CharField(blank=True, choices=[('application_security', 'Обеспечение заявки'), ('contract_execution', 'Исполнение контракта'), ('advance_return', 'Возврат аванса'), ('warranty_obligations', 'Гарантийные обязательства'), ('payment_guarantee', 'Гарантии оплаты товара'), ('customs_guarantee', 'Таможенные гарантии'), ('vat_refund', 'Возмещение НДС')], default='', max_length=30, verbose_name='Тип гарантии')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма')),
                ('term_months', models.IntegerField(blank=True, null=True, verbose_name='Срок (месяцы)')),
                ('source', models.CharField(choices=[('website_calculator', 'Калькулятор на сайте'), ('website_form', 'Форма на сайте'), ('landing_page', 'Лендинг'), ('phone', 'Телефонный звонок'), ('other', 'Другое')], default='website_calculator', max_length=30, verbose_name='Источник')),
                ('utm_source', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM Campaign')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('qualified', 'Квалифицирован'), ('converted', 'Конвертирован в заявку'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата контакта')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('converted_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='applications.application', verbose_name='Созданная заявка')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
