# Generated by Django 5.0.4 on 2026-01-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Создание заявки'), ('pending', 'Отправка на скоринг'), ('in_review', 'На рассмотрении в банке'), ('info_requested', 'Возвращение на доработку'), ('approved', 'Одобрен'), ('rejected', 'Отказано'), ('won', 'Выдан'), ('lost', 'Не выдан')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='applicationstatusdefinition',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('draft', 'Создание заявки'), ('pending', 'Отправка на скоринг'), ('in_review', 'На рассмотрении в банке'), ('info_requested', 'Возвращение на доработку'), ('approved', 'Одобрен'), ('rejected', 'Отказано'), ('won', 'Выдан'), ('lost', 'Не выдан')], default='', help_text='Маппинг на внутренний статус (draft, pending, approved, etc.)', max_length=20, verbose_name='Внутренний статус'),
        ),
    ]
