# Generated by Django 6.0 on 2026-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Внутренние заметки администратора (не видны клиенту)', verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='application',
            name='info_request_message',
            field=models.TextField(blank=True, default='', help_text='Сообщение при запросе дополнительной информации', verbose_name='Сообщение запроса информации'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Причина отклонения заявки (заполняется администратором)', verbose_name='Причина отклонения'),
        ),
    ]
