# Generated by Django 6.0 on 2026-01-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_add_admin_notes_and_rejection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='insurance_category',
            field=models.CharField(blank=True, choices=[('smr', 'Строительно-монтажные риски'), ('contract', 'Контракта'), ('personnel', 'Персонал'), ('transport', 'Транспорт'), ('property', 'Имущество'), ('liability', 'Ответственность')], default='', help_text='Персонал/Транспорт/Имущество/Ответственность', max_length=30, verbose_name='Категория страхования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='insurance_product_type',
            field=models.CharField(blank=True, choices=[('smr_full', 'СМР полный пакет'), ('smr_basic', 'СМР базовый'), ('smr_risks', 'Страхование строительных рисков'), ('contract_execution', 'Страхование исполнения контракта'), ('contract_liability', 'Страхование ответственности по контракту'), ('dms', 'Добровольное медицинское страхование (ДМС)'), ('critical_illness', 'Страхование критических заболеваний'), ('accident', 'Страхование несчастных случаев'), ('travel', 'Комплексное страхование в поездках'), ('osago', 'ОСАГО юридических лиц'), ('fleet', 'Комплексное страхование автопарков'), ('special_tech', 'Страхование специальной техники'), ('carrier_liability', 'Страхование ответственности перевозчика'), ('construction', 'Страхование объектов строительства'), ('cargo', 'Страхование грузов и перевозок'), ('company_property', 'Страхование имущества компаний'), ('business_interruption', 'Страхование перерывов деятельности'), ('civil_liability', 'Страхование гражданской ответственности'), ('hazardous_objects', 'Страхование опасных объектов'), ('professional_risks', 'Страхование профессиональных рисков'), ('quality_liability', 'Страхование ответственности за качество')], default='', help_text='Подтип страхования (ДМС, ОСАГО, и т.д.)', max_length=40, verbose_name='Страховой продукт'),
        ),
    ]
