# Generated by Django 6.0 on 2026-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_add_smr_contract_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='credit_sub_type',
            field=models.CharField(blank=True, choices=[('express', 'Экспресс-кредит'), ('working_capital', 'Кредит на пополнение оборотных средств'), ('corporate', 'Корпоративный кредит')], default='', help_text='Подтип кредита (только для corporate_credit)', max_length=30, verbose_name='Тип кредита'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tender_law',
            field=models.CharField(blank=True, choices=[('44_fz', '44-ФЗ'), ('223_fz', '223-ФЗ'), ('615_pp', '615-ПП'), ('185_fz', '185-ФЗ'), ('275_fz', '275-ФЗ'), ('kbg', 'КБГ (Коммерческая)'), ('commercial', 'Коммерческий')], default='', help_text='Федеральный закон (44-ФЗ, 223-ФЗ, 185-ФЗ, КБГ)', max_length=20, verbose_name='Закон о закупках'),
        ),
    ]
