# Generated by Django 5.0.4 on 2026-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_lead_page_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdecision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('info_requested', 'Возвращение на доработку')], max_length=20, verbose_name='Решение'),
        ),
    ]
