# Generated by Django 6.0 on 2026-02-01 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_lead_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True когда сообщение прочитано получателем', verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано пользователем'),
        ),
    ]
