# Generated by Django 6.0 on 2026-02-02 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_alter_application_status_and_more'),
        ('companies', '0012_add_mchd_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Может быть пустым для заявок из лидов до привязки клиента', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.companyprofile', verbose_name='Компания'),
        ),
    ]
