# Generated by Django 6.0 on 2026-03-01 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_application_company_nullable'),
        ('companies', '0014_alter_companyprofile_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Может быть пустым для заявок из лидов до привязки клиента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='companies.companyprofile', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_applications', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='calculationsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_sessions', to='companies.companyprofile', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='calculationsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='leadcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='partnerdecision',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
