# Generated by Django 5.0.4 on 2025-12-26 17:08

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='Файл')),
                ('document_type', models.CharField(choices=[('constituent', 'Учредительные'), ('financial', 'Финансовые'), ('tax', 'Налоговые'), ('permit', 'Разрешительные'), ('other', 'Прочие')], default='other', max_length=20, verbose_name='Тип документа')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('verified', 'Проверен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.companyprofile', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
