# Generated by Django 6.0 on 2025-12-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport_all_pages', 'Паспорт (все страницы)'), ('founder_passport', 'Паспорт учредителя'), ('appointment_order', 'Приказ о назначении директора'), ('statute', 'Устав'), ('lease_contract', 'Договор аренды'), ('account_card_51', 'Карточка 51 счета'), ('account_card_60_62', 'Карточка 60/62 счета'), ('balance_sheet_f1', 'Бухгалтерский баланс Ф1'), ('financial_results_f2', 'Отчет о прибылях и убытках Ф2'), ('tax_declaration', 'Налоговая декларация'), ('osv_all', 'ОСВ (общая)'), ('contract_register', 'Реестр контрактов'), ('executed_contracts', 'Исполненные контракты'), ('other', 'Прочие')], default='other', max_length=30, verbose_name='Тип документа'),
        ),
    ]
