# Generated by Django 5.0.4 on 2026-01-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_populate_document_types_appendix_b'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttypedefinition',
            name='unique_doc_type_per_product',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_documen_794628_idx',
            old_name='documents_d_doc_type_prod_idx',
        ),
        migrations.RenameIndex(
            model_name='documenttypedefinition',
            new_name='documents_d_product_ed37f2_idx',
            old_name='documents_d_product_abc123_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documenttypedefinition',
            unique_together={('document_type_id', 'product_type')},
        ),
    ]
