# Generated by Django 6.0 on 2026-01-09 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_agent_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type_name', models.CharField(help_text='Название запрашиваемого документа', max_length=500, verbose_name='Название документа')),
                ('document_type_id', models.IntegerField(blank=True, help_text='Опциональный ID типа из Приложения Б', null=True, verbose_name='ID типа документа')),
                ('comment', models.TextField(blank=True, default='', help_text='Дополнительные указания для пользователя', verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('fulfilled', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('fulfilled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='documents.document', verbose_name='Предоставленный документ')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_document_requests', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос документа',
                'verbose_name_plural': 'Запросы документов',
                'ordering': ['-created_at'],
            },
        ),
    ]
