# Generated by Django 6.0 on 2026-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='e.g. /credit-for-business. Do not include domain.', max_length=255, unique=True, verbose_name='URL Path')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('h1_title', models.CharField(blank=True, max_length=255, verbose_name='H1 Title')),
                ('main_description', models.TextField(blank=True, help_text='Text content for the main block', verbose_name='Main Description')),
                ('faq', models.JSONField(blank=True, default=list, help_text='List of {question, answer} objects', verbose_name='FAQ')),
                ('popular_searches', models.JSONField(blank=True, default=list, help_text='List of {text, href} objects', verbose_name='Popular Searches')),
                ('bank_offers', models.JSONField(blank=True, default=list, help_text='Configuration for the 9 offers block', verbose_name='Bank Offers Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
            },
        ),
    ]
