# Generated by Django 5.0.4 on 2026-01-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_conditions', '0002_populate_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='e.g. /credit-for-business. Do not include domain.', max_length=255, unique=True, verbose_name='URL Path')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('h1_title', models.CharField(blank=True, max_length=255, verbose_name='H1 Title')),
                ('main_description', models.TextField(blank=True, help_text='Text content for the main block', verbose_name='Main Description')),
                ('faq', models.JSONField(blank=True, default=list, help_text='List of {question, answer} objects', verbose_name='FAQ')),
                ('popular_searches', models.JSONField(blank=True, default=list, help_text='List of {text, href} objects', verbose_name='Popular Searches')),
                ('bank_offers', models.JSONField(blank=True, default=list, help_text='Configuration for 9 offers block', verbose_name='Bank Offers Configuration')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('page_type', models.CharField(choices=[('landing', 'Landing Page'), ('product', 'Product Page'), ('custom', 'Custom Page')], default='product', max_length=50, verbose_name='Page Type')),
                ('template_name', models.CharField(blank=True, help_text='Template to apply on creation (e.g., factoring, rko, leasing)', max_length=100, verbose_name='Template Name')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shown first in catch-all routes', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banks', models.ManyToManyField(blank=True, related_name='seo_pages', to='bank_conditions.bank', verbose_name='Banks to Display')),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'ordering': ['-priority', 'slug'],
            },
        ),
    ]
