# Generated by Django 6.0 on 2026-01-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='h2_title',
            field=models.CharField(blank=True, help_text='Secondary heading', max_length=255, verbose_name='H2 Title'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='h3_title',
            field=models.CharField(blank=True, help_text='Tertiary heading', max_length=255, verbose_name='H3 Title'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main block image', null=True, upload_to='seo/hero/', verbose_name='Hero Image'),
        ),
    ]
