# Generated by Django 6.0 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_add_h2_h3_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='application_button_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Application Button Text'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='application_form_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Application Form Title'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='best_offers_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Best Offers Title'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='hero_button_href',
            field=models.CharField(blank=True, default='#application', help_text='Can be anchor (#application), local path (/contact), or full URL', max_length=255, verbose_name='Hero Button URL'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='hero_button_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Hero Button Text'),
        ),
    ]
