# Generated by Django 6.0 on 2026-02-08

from django.db import migrations, models


AUTOFILL_PRESETS = {
    'factoring',
    'rko',
    'leasing',
    'guarantees',
    'credits',
    'deposits',
    'ved',
    'insurance',
    'tender',
    'checking',
}


def migrate_template_name_to_autofill_template(apps, schema_editor):
    SeoPage = apps.get_model('seo', 'SeoPage')

    for page in SeoPage.objects.all().iterator():
        template_name = (page.template_name or '').strip()
        if not template_name:
            continue

        if template_name in AUTOFILL_PRESETS:
            update_fields = []

            if not (page.autofill_template or '').strip():
                page.autofill_template = template_name
                update_fields.append('autofill_template')

            # Preset values in template_name are legacy behavior.
            # Keep template_name for layout templates only (e.g. create-page).
            page.template_name = ''
            update_fields.append('template_name')

            page.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_add_create_page_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='autofill_template',
            field=models.CharField(blank=True, default='', help_text='Content preset for autofill (e.g., factoring, rko, leasing)', max_length=100, verbose_name='Autofill Template'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='template_name',
            field=models.CharField(blank=True, default='', help_text='Layout template for rendering (e.g., create-page)', max_length=100, verbose_name='Layout Template'),
        ),
        migrations.RunPython(migrate_template_name_to_autofill_template, migrations.RunPython.noop),
    ]
